class RenderErr(Exception): pass
class StyleErr(Exception): pass
class MockErr(Exception): pass
class MinifyErr(Exception): pass
class PreviewErr(Exception): pass
class ConcatErr(Exception): pass
class JoinErr(Exception): pass
class EvalErr(Exception): pass
class CompErr(Exception): pass
class HelperErr(Exception): pass
class GridErr(Exception): pass
